### ISSUE TITLE
hostsctl Enable awk: invalid -v option

### ISSUE THREAD

**Issue by Br0ken-Dev** [pigmonkey/hostsctl#1]
Any questions should be directed to @0xl3vi.
when typing sudo enable host.com presents the error "awk: invalid -v option" Not sure what its doing but it is breaking the remote hosts file and wiping it clean

**Comment by pigmonkey** [comment]
What awk are you using? This may be a GNU awk vs BSD awk issue.

**Comment by Br0ken-Dev** [comment]
Im using BSD awk.

**Comment by pigmonkey** [comment]
Yeah, that's BSD awk. Looks like `-v` is GNU-only.

Can you try the latest commit and see if it works for you?

**Comment by Br0ken-Dev** [comment]
When trying to tod hostsctl update i not get this error. 
/usr/local/bin/hostsctl: line 259: [: : integer expression expected
/usr/local/bin/hostsctl: line 262: "" - "": syntax error: operand expected (error token is """ - """)

**Comment by pigmonkey** [comment]
You got past awk this time, so that's progress. Give the latest commit another shot.

(Thanks for being the macOS tester.)

**Comment by Br0ken-Dev** [comment]
Its a good install and update works perfectly. No more issues as far as i can tell on macOS 10.12.5
