### ISSUE TITLE
`hosts_clean()` causes an erroneous status code when no tmpfiles exit

### ISSUE THREAD

**Issue by sudoforge** [pigmonkey/hostsctl#2]
## Steps to reproduce

* `hostsctl (enable|disable) <host>`: successful operation
* `echo $?`: returns `1`

The above is simply an example. Any time the script operates and does not create anything that matches `/tmp/hostsctl-*`, an erroneous status code of `1` will be returned. This is because `rm` fails when the argument doesn't exist.

The function currently pipes `stderr` to `/dev/null`, but all this does is hide any text that is printed to the console. The status code remains.

This can be avoided by wrapping `rm /tmp/hostsctl-*` in `trap`.

**Comment by pigmonkey** [comment]
Nice catch. Thanks.
