### ISSUE TITLE
hostsctl update fetches 0 records when mawk is installed

### ISSUE THREAD

**Issue by ikysil** [pigmonkey/hostsctl#9]
## Bug report

`hostsctl update` fetches 0 records when `mawk` is installed.

Platform: Ubuntu 19.10

Workaround: install gawk

Steps to reproduce:
```
$ sudo hostsctl update
✓ update: 0 modified entries

$ wc -l /etc/hostsctl/remote.hosts 
0 /etc/hostsctl/remote.hosts

$ sudo apt install gawk

$ sudo hostsctl update
✓ update: 43000 modified entries

$ wc -l /etc/hostsctl/remote.hosts 
43000 /etc/hostsctl/remote.hosts

$ sudo apt remove gawk
...
Removing gawk (1:4.2.1+dfsg-1.1build1) ...
update-alternatives: using /usr/bin/mawk to provide /usr/bin/awk (awk) in auto mode

$ sudo hostsctl update
✓ update: 43000 modified entries

$ wc -l /etc/hostsctl/remote.hosts 
0 /etc/hostsctl/remote.hosts

$ sudo hostsctl update
✓ update: 0 modified entries

$ wc -l /etc/hostsctl/remote.hosts 
0 /etc/hostsctl/remote.hosts
```

Analysis:
* with mawk:
```
$ echo 0.0.0.0 | awk '{print substr($0,0,3)}'
0.
```

* with gawk:
```
$ echo 0.0.0.0 | awk '{print substr($0,0,3)}'
0.0
```

**Comment by pigmonkey** [comment]
The [documentation for gawk](https://linux.die.net/man/1/awk) says:

    substr(s, i [, n])
    
    Returns the at most n-character substring of s starting at i. If n is omitted, the rest of s is used.

The [documention for mawk](https://linux.die.net/man/1/mawk) says:

    substr(s,i,n) substr(s,i)

    Returns the substring of string s, starting at index i, of length n. If n is omitted, the suffix of s, starting at i is returned.

So is should act the same in both. This seems like it may be a bug in mawk's implantation of `substr`, since in your example it is not respecting `n = 3`.

**Comment by pigmonkey** [comment]
I tried installing mawk and I don't experience this problem.

    $ echo 0.0.0.0 | awk '{print substr($0,0,3)}'
    0.0
    $ mawk -W version
    mawk 1.3.4 20190203
    Copyright 2008-2018,2019, Thomas E. Dickey
    Copyright 1991-1996,2014, Michael D. Brennan
    
    random-funcs:       srandom/random
    regex-funcs:        internal
    compiled limits:
    sprintf buffer      8192
    maximum-integer     2147483647

Perhaps this was a mawk bug, and Ubuntu is shipping and older, unpatched version.

**Comment by ikysil** [comment]
Yes, I have a much older version:

```
$ mawk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
```

**Comment by ikysil** [comment]
Here is a discussion on the Ubuntu side:
https://bugs.launchpad.net/ubuntu/+source/mawk/+bug/1841654
Consider replacing mawk with gawk in main

Would you consider a PR to add a check to install.sh for a buggy version of awk and output a warning?

**Comment by pigmonkey** [comment]
Yes, I think a warning in the install script would be reasonable given Ubuntu's prevalence. It would probably be best to do the same `echo ... | awk ...` test we've been doing here and checking that the output is as expected, rather than trying to check for specific implementations or versions.

**Comment by ikysil** [comment]
> It would probably be best to do the same `echo ... | awk ...` test we've been doing here and checking that the output is as expected, rather than trying to check for specific implementations or versions.

Yes, that's exactly what I was thinking about. I will prepare a PR.

**Comment by ikysil** [comment]
I found these lines from `bin/hostsctl.sh` suspicious:
```bash
  # Only allow entries in the new remote file which begin with the blocking IP
  # address.
  match_string="$(echo $ip | awk '{print substr($0,0,3)}')"
  hosts=$(awk "{ if ( substr(\$0, 1, 3) == \"$match_string\" ) print \$0 >> \"${tmpfile0}\" }" "${tmpfile}")
```

The invocations of `substr` use different starting index.

Unfortunately, neither https://linux.die.net/man/1/mawk nor https://linux.die.net/man/1/awk specifies if index of `substr` is 0-based or 1-based. The only hint I could find is in the description of `index`:

> index(s,t)
If t is a substring of s, then the position where t starts is returned, else 0 is returned. The first character of s is in position 1.

> index(s, t)
Returns the index of the string t in the string s, or 0 if t is not present. (This implies that character indices start at one.)

Let's test:
```bash
$ echo 0.0.0.0 | mawk '{print substr($0,0,3)}'
0.

$ echo 0.0.0.0 | gawk '{print substr($0,0,3)}'
0.0

$ echo 0.0.0.0 | mawk '{print substr($0,1,3)}'
0.0

$ echo 0.0.0.0 | gawk '{print substr($0,1,3)}'
0.0
```

Looks like we just need to use the same starting index (of 1):
```bash
  # Only allow entries in the new remote file which begin with the blocking IP
  # address.
  match_string="$(echo $ip | awk '{print substr($0,1,3)}')"
  hosts=$(awk "{ if ( substr(\$0, 1, 3) == \"$match_string\" ) print \$0 >> \"${tmpfile0}\" }" "${tmpfile}")
```

Both `hosts_fetch_updates` and `hosts_list` are affected.

**Comment by ikysil** [comment]
PR #10

**Comment by pigmonkey** [comment]
Good catch. It is weird that gawk (and the version of mawk that I installed) exhibits no change with either index.
